### PR TITLE
Add caching to tests

### LINKED ISSUE #37: Add caching to tests
There are some opportunities to cache the tests in the CI. This should save some 1.5 minutes off the tests.

I also noticed that the CI runs tests twice in a PR, because it is configured to run on every push as well as on a PR. We can scope this to master to avoid it.

- [x] Python installation
- [x] SOCRATES compilation
- [x] Avoid running the same tests twice in pull requests
- [ ] Cache `FWL_DATA` directory

### PR DESCRIPTION
**Pull request by stefsmeets**
This PR sets up caching for setting up JANUS and SOCRATES. This completely eliminates build times on repeated runs with the same SOCRATES or JANUS versions. This should reduce total test times by ~1.5 minutes for each run.

The caches are keyed by the python version and `pyproject.toml` for JANUS and to `SOCRATES/version` for SOCRATES.

I also scoped the test runs, so that they no longer run twice in a PR.

Closes #37

### TODO
- [x] Cache `FWL_DATA` directory
- [x] Use absolute path for `FWL_DATA`

### CODE REVIEW

**Comment by stefsmeets** [comment]
This PR is ready to be reviewed.

**Comment by timlichtenberg** [comment]
I am happy to review it, since Laurent is on holiday this week. So if you are ok with this, I will go ahead.

**Review by timlichtenberg — APPROVED** [review]
Seems good to me, before merging we may want to quickly discuss this with Laurent early next week when he's back; up to you.

**Comment by stefsmeets** [comment]
Cheers, I'll just merge it now then. If there need to be additional changes, I'm happy to fix it!

**Pull request merged**
