### PR TITLE
Set up coverage testing

### PR DESCRIPTION
**Pull request by stefsmeets**
This PR sets up coverage testing. I updated CONTRIBUTING.md with how to get started. The test workflow will report the coverage to the action artifacts and as a badge in the readme.

See: https://github.com/FormingWorlds/JANUS/blob/coverage/README.md

### TODO
- [x] Add GIST_TOKEN to secrets

### CODE REVIEW

**Comment by timlichtenberg** [comment]
Gave you access to administrative actions on JANUS. Sufficient?

**Comment by stefsmeets** [comment]
Thanks @timlichtenberg , should be good now! Would you be willing to review this?

**Comment by timlichtenberg** [comment]
Sure, since Laurent is not here this week though, it will be good if also @nichollsh has a look on your PRs this week. We should discuss PR organisation at one of the next PROTEUS meetings.

**Review by nichollsh — APPROVED** [review]
Looks good. Getting some ideas as to the code coverage will be useful, and should probably also be done for PROTEUS at some point in the future too.

**Review by timlichtenberg — APPROVED** [review]
Same here, looks good to me.

**Comment by stefsmeets** [comment]
Example coverage: https://github.com/FormingWorlds/JANUS/actions/runs/10061102573#summary-27810317683

**Pull request merged**
