### PR TITLE
Automate installation of SOCRATES

### LINKED ISSUE #24: Provide Socrates executables
Currently, compilation of the socrates code is mandatory. We would like to simplify this step by directly providing executables to download for different OS. Two executables are used by JANUS `prep_spec` and `Cl_run_cdf`. We might however change this and use the socrates library instead (radlib.a), as it is done in AGNI.

### PR DESCRIPTION
**Pull request by stefsmeets**
This PR tracks my attemps to download and install SOCRATES.

The way it work at the moment is that `janus download socrates` downloads and compiles SOCRATES. Janus downloads SOCRATES to the `/home/stef/.local/share/socrates/` directory.

You can also set the environment variable `SOCRATES`, this takes precedence. For example:

```console
SOCRATES=/path/to/socrates pytest
```

Closes #24

### CODE REVIEW

**Comment by stefsmeets** [comment]
@timlichtenberg

**Comment by stefsmeets** [comment]
Hi @nichollsh , this PR is ready for review, let me know what you think!

**Comment by timlichtenberg** [comment]
> @timlichtenberg

You don't have to do this, forget my comment from last week.  ;)

**Review by nichollsh — APPROVED** [review]
Looks good! Makes sense to depend on the configure and build scripts in the SOCRATES repo, but this makes the actual setup of the code much more user friendly.

**Pull request merged**
