### PR TITLE
Set up documentation on readthedocs

### PR DESCRIPTION
**Pull request by stefsmeets**
This PR sets up documentation on readthedocs. Once this PR is merged you can see the docs on https://fwl-janus.readthedocs.io 

Test version for now: https://fwl-janus.readthedocs.io/en/rtd/

### CODE REVIEW

**Comment by stefsmeets** [comment]
@timlichtenberg could you have a look at this and let me know what you think?

**Comment by timlichtenberg** [comment]
Will do, just waiting for the tests to have passed.

**Review by timlichtenberg — APPROVED** [review]
Looks great, much nicer layout than the current PROTEUS docs. URL and layout should be homogenised in the PROTEUS once we get there.

**Comment by stefsmeets** [comment]
Ah, I see proteus uses sphinx. I also prefer the layout of mkdocs and its much easier to work with imo. We can transfer proteus to mkdocs as well if you like.

**Pull request merged**
