### PR TITLE
Set up documentation using mkdocs

### LINKED ISSUE #29: Create Documentation
Create a read the docs page to:
- give installation instructions
- show basic usage/worksflow
- list config file options

Also we could turn the scripts in the example folder into notebooks.

### PR DESCRIPTION
**Pull request by stefsmeets**
This PR sets up documentation using mkdocs. You can build the documentation for yourself like this:

```console
pip install -e .[docs]
mkdocs serve
```

Once this is merged I'm happy to set up documentation on readthedocs under https://fwljanus.readthedocs.io

Closes #29

### CODE REVIEW

**Comment by timlichtenberg** [comment]
So my only point why hesitating with this is the consideration of whether we want to have individual docs for all sub-modules, or whether they should all be incorporated into proteus documentation. I cannot exactly remember anymore whether we agreed this was the best solution or not, we discussed this at one of the last meetings.

**Comment by stefsmeets** [comment]
This can be solved afterwards using subprojects: https://docs.readthedocs.io/en/stable/subprojects.html

**Comment by timlichtenberg** [comment]
Awesome, this sounds good to me then!

**Review by timlichtenberg — APPROVED** [review]

**Comment by stefsmeets** [comment]
If I have time tomorrow I will set this up on readthedocs.

**Pull request merged**
